[package]
name = "beacon-core"
version = "1.5.2"
edition = "2021"

[dependencies]
futures = { workspace=true}
futures-util = { workspace=true}
bytes = { workspace=true}
anyhow = { workspace=true}
tempfile = { workspace=true}
serde = { workspace=true}
serde_json = { workspace=true}
utoipa = { workspace=true}
typetag =  { workspace=true}
async-trait = { workspace=true }
datafusion = { workspace=true }
geodatafusion = { workspace=true }
arrow = { workspace=true}
glob = { workspace = true}
tokio = { workspace = true }
indexmap = { workspace = true }
object_store = { workspace = true }
async-stream = "0.3.6"
parking_lot = { workspace = true}
sysinfo = { version = "0.35.2", features = ["serde"]}
uuid = "1.16.0"
inventory = "0.3.18"
pathdiff = "0.2.3"

tracing = { workspace=true}
# Local dependencies
beacon-config = { path = "../beacon-config" }
beacon-arrow-netcdf = { path = "../beacon-arrow-netcdf" }
beacon-arrow-odv = { path = "../beacon-arrow-odv" }
beacon-query = { path = "../beacon-query" }
beacon-functions = { path = "../beacon-functions" }
beacon-planner = { path = "../beacon-planner" }
beacon-data-lake = { path = "../beacon-data-lake" }
beacon-formats = { path = "../beacon-formats" }
beacon-object-storage = { path = "../beacon-object-storage" }