[package]
name = "beacon-arrow-netcdf"
version = "1.4.0"
edition = "2021"

[dependencies]
netcdf = { git ="https://github.com/robinskil/netcdf.git", features = ["ndarray"], version = "0.11.1"}
netcdf-sys = { git ="https://github.com/robinskil/netcdf.git", package = "netcdf-sys" }
nd-arrow-array = { git = "https://github.com/maris-development/nd-arrow-array.git", branch = "main", version = "1.3.0" }
arrow = { workspace = true }
arrow-schema = { workspace = true }
anyhow = { workspace=true }
tempfile = { workspace=true}
futures = { workspace=true }
indexmap = { workspace=true }
thiserror = { workspace=true }
ndarray = "0.17.1"
hifitime = "4.0.2"
regex = "1.11.1"
num-traits = "0.2.19"
tracing = { workspace = true }
serde = { workspace = true }